export const villes = [
  { name: 'Banikoara' },
  { name: 'Gogonou' },
  { name: 'Kandi' },
  { name: 'Karimama' },
  { name: 'Malanville' },
  { name: 'Ségbana' },
  { name: 'Cobli' },
  { name: 'Kérou' },
  { name: 'Kouandé' },
  { name: 'Matéri' },
  { name: 'Natitingou Péhunco' },
  { name: 'Tanguiéta' },
  { name: 'Toukountouna' },
  { name: 'Boukoumbé' },
  { name: 'Abomey-Calavi' },
  { name: 'Allada' },
  { name: 'Kpomassè' },
  { name: 'Ouidah' },
  { name: 'Sô-Ava' },
  { name: 'Toffo' },
  { name: 'Tori' },
  { name: 'Zê' },
  { name: 'Bembèrèkè' },
  { name: 'Kalalé' },
  { name: 'N’Dali' },
  { name: 'Nikki' },
  { name: 'Parakou' },
  { name: 'Pèrèrè' },
  { name: 'Sinendé' },
  { name: 'Tchaourou' },
  { name: 'Bantè' },
  { name: 'Dassa-Zoumè' },
  { name: 'Glazoué' },
  { name: 'Ouessè' },
  { name: 'Savalou' },
  { name: 'Savè' },
  { name: 'Aplahoué' },
  { name: 'Djakotomey' },
  { name: 'Dogbo' },
  { name: 'Klouékanmey' },
  { name: 'Lalo' },
  { name: 'Toviklin' },
  { name: 'Bassila' },
  { name: 'Copargo' },
  { name: 'Djougou' },
  { name: 'Ouaké' },
  { name: 'Athiémé' },
  { name: 'Bopa' },
  { name: 'Comè' },
  { name: 'Grand-Popo' },
  { name: 'Houéyogbé' },
  { name: 'Lokossa' },
  { name: 'Adjarra' },
  { name: 'Adjohoun' },
  { name: 'Aguégués' },
  { name: 'Akpro-Missérété' },
  { name: 'Avrankou' },
  { name: 'Bonou' },
  { name: 'Dangbo' },
  { name: 'Porto-Novo' },
  { name: 'Sèmè-Podji' },
  { name: 'Adja-ouèrè' },
  { name: 'Ifangni' },
  { name: 'Kétou' },
  { name: 'Pobè' },
  { name: 'Sakété' },
  { name: 'Abomey' },
  { name: 'Agbangnizoun' },
  { name: 'Bohicon' },
  { name: 'Covè' },
  { name: 'Djidja' },
  { name: 'Ouinhi' },
  { name: 'Zagnanado' },
  { name: 'Za-kpota' },
  { name: 'Zogbodomè' },
  { name: 'Cotonou' },
];
export const departement = [
  {
    name: 'Alibori',
    cities: [
      { cname: 'Banikoara' },
      { cname: 'Gogonou' },
      { cname: 'Kandi' },
      { cname: 'Karimama' },
      { cname: 'Malanville' },
      { cname: 'Ségbana' },
    ],
  },
  {
    name: 'Atacora',
    cities: [
      { cname: 'Cobli' },
      { cname: 'Kérou' },
      { cname: 'Kouandé' },
      { cname: 'Matéri' },
      { cname: 'Natitingou Péhunco' },
      { cname: 'Tanguiéta' },
      { cname: 'Toukountouna' },
      { cname: 'Boukoumbé' },
    ],
  },
  {
    name: 'Atlantique',
    cities: [
      { cname: 'Abomey-Calavi' },
      { cname: 'Allada' },
      { cname: 'Kpomassè' },
      { cname: 'Ouidah' },
      { cname: 'Sô-Ava' },
      { cname: 'Toffo' },
      { cname: 'Tori' },
      { cname: 'Zê' },
    ],
  },
  {
    name: 'Borgou',
    cities: [
      { cname: 'Bembèrèkè' },
      { cname: 'Kalalé' },
      { cname: 'N’Dali' },
      { cname: 'Nikki' },
      { cname: 'Parakou' },
      { cname: 'Pèrèrè' },
      { cname: 'Sinendé' },
      { cname: 'Tchaourou' },
    ],
  },
  {
    name: 'Collines',
    cities: [
      { cname: 'Bantè' },
      { cname: 'Dassa-Zoumè' },
      { cname: 'Glazoué' },
      { cname: 'Ouessè' },
      { cname: 'Savalou' },
      { cname: 'Savè' },
    ],
  },
  {
    name: 'Couffo',
    cities: [
      { cname: 'Aplahoué' },
      { cname: 'Djakotomey' },
      { cname: 'Dogbo' },
      { cname: 'Klouékanmey' },
      { cname: 'Lalo' },
      { cname: 'Toviklin' },
    ],
  },
  // Donga
  {
    name: 'Donga',
    cities: [
      { cname: 'Bassila' },
      { cname: 'Copargo' },
      { cname: 'Djougou' },
      { cname: 'Ouaké' },
    ],
  },
  {
    name: 'Litoral',
    cities: [{ cname: 'Cotonou' }],
  },
  {
    name: 'Mono',
    cities: [
      { cname: 'Athiémé' },
      { cname: 'Bopa' },
      { cname: 'Comè' },
      { cname: 'Grand-Popo' },
      { cname: 'Houéyogbé' },
      { cname: 'Lokossa' },
    ],
  },
  {
    name: 'Ouémé',
    cities: [
      { cname: 'Adjarra' },
      { cname: 'Adjohoun' },
      { cname: 'Aguégués' },
      { cname: 'Akpro-Missérété' },
      { cname: 'Avrankou' },
      { cname: 'Bonou' },
      { cname: 'Dangbo' },
      { cname: 'Porto-Novo' },
      { cname: 'Sèmè-Podji' },
    ],
  },
  {
    name: 'Plateau',
    cities: [
      { cname: 'Adja-ouèrè' },
      { cname: 'Ifangni' },
      { cname: 'Kétou' },
      { cname: 'Pobè' },
      { cname: 'Sakété' },
    ],
  },
  {
    name: 'Zou',
    cities: [
      { cname: 'Abomey' },
      { cname: 'Agbangnizoun' },
      { cname: 'Bohicon' },
      { cname: 'Covè' },
      { cname: 'Djidja' },
      { cname: 'Ouinhi' },
      { cname: 'Zagnanado' },
      { cname: 'Za-kpota' },
      { cname: 'Zogbodomè' },
    ],
  },
];